create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text unique not null,
  role text not null default 'contributor' check (role in ('contributor', 'lead', 'admin')),
  shift text,
  meet_link text,
  is_active boolean not null default true,
  last_seen_at timestamptz,
  lead_id uuid references public.profiles(id) on delete set null,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- profiles already exists in production, so create table above is a no-op there;
-- this is what actually adds the columns to the live database.
alter table public.profiles add column if not exists last_seen_at timestamptz;
alter table public.profiles add column if not exists lead_id uuid references public.profiles(id) on delete set null;
alter table public.profiles add column if not exists avatar_url text;

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  email text,
  event text not null check (event in ('login', 'login_failed', 'logout')),
  user_agent text,
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text unique not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- A project may have more than one lead, so assignment lives in its own
-- join table rather than a single lead_id column on projects.
create table if not exists public.project_leads (
  project_id bigint not null references public.projects(id) on delete cascade,
  lead_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (project_id, lead_id)
);

-- A contributor's rank is scored per project, not globally: a project has
-- its own contributor/l0/l1/l10 tiers, and the same person can hold a
-- different tier on each project they work on.
create table if not exists public.contributor_project_levels (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  level text not null default 'contributor' check (level in ('contributor', 'l0', 'l1', 'l10')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, project_id)
);

create table if not exists public.task_submissions (
  id bigint generated by default as identity primary key,
  task_id text,
  cb_email text not null,
  user_id uuid references public.profiles(id) on delete set null,
  project_id bigint references public.projects(id) on delete set null,
  stage text not null default 'attempt' check (stage in ('attempt', 'l0', 'l1')),
  status text not null default 'in_progress' check (status in ('submitted', 'in_progress', 'empty', 'expired', 'claimed_by_another')),
  notes text,
  date date,
  submitted_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.weekly_targets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  week_start date not null,
  target integer not null default 50,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, week_start)
);

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  category text not null,
  title text not null,
  url text not null,
  project_id bigint references public.projects(id) on delete set null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.house_rules (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(id) on delete set null,
  type text not null default 'rule' check (type in ('info', 'rule')),
  title text,
  body text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) > 0),
  read_at timestamptz,
  -- Deletion is per-viewer ("delete for me"): each side can hide a message
  -- from their own view without removing it for the other person.
  deleted_by_sender boolean not null default false,
  deleted_by_recipient boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists task_submissions_user_id_idx on public.task_submissions(user_id);
create index if not exists task_submissions_cb_email_idx on public.task_submissions(cb_email);
create index if not exists task_submissions_date_idx on public.task_submissions(date);
-- Enforces one row per Task ID; multiple NULLs are still allowed since a
-- unique index treats each NULL as distinct.
create unique index if not exists task_submissions_task_id_key on public.task_submissions(task_id);
create index if not exists resources_project_category_idx on public.resources(project_id, category, sort_order);
create index if not exists house_rules_project_idx on public.house_rules(project_id, sort_order);
create index if not exists activity_logs_created_at_idx on public.activity_logs(created_at desc);
create index if not exists activity_logs_user_id_idx on public.activity_logs(user_id);
create index if not exists profiles_lead_id_idx on public.profiles(lead_id);
create index if not exists contributor_project_levels_user_idx on public.contributor_project_levels(user_id);
create index if not exists contributor_project_levels_project_idx on public.contributor_project_levels(project_id);
create index if not exists messages_sender_idx on public.messages(sender_id, created_at);
create index if not exists messages_recipient_idx on public.messages(recipient_id, created_at);

create or replace function public.is_active_user()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and is_active) $$;

create or replace function public.is_manager()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and is_active and role in ('lead', 'admin')) $$;

-- Admins manage everyone; leads are scoped to their attached contributors
-- (see is_own_or_attached below) rather than the whole roster.
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and is_active and role = 'admin') $$;

-- True when profile_id is the caller's own id, or a contributor whose
-- lead_id points back at the caller. Used both for a profiles row (by its
-- id) and for a task_submissions/weekly_targets row (by its user_id).
create or replace function public.is_own_or_attached(profile_id uuid)
returns boolean language sql stable security definer set search_path = public
as $$
  select profile_id = auth.uid()
    or exists (select 1 from public.profiles where id = profile_id and lead_id = auth.uid())
$$;

-- Messaging is open to any active user regardless of lead attachment, so it
-- needs its own minimal, RLS-independent lookup rather than the profiles
-- table's (deliberately) scoped read policy.
-- Dropped first since CREATE OR REPLACE can't change a function's return type
-- (this one gained avatar_url after its first release).
drop function if exists public.directory();
create function public.directory()
returns table (id uuid, name text, is_active boolean, last_seen_at timestamptz, avatar_url text)
language sql stable security definer set search_path = public
as $$ select id, name, is_active, last_seen_at, avatar_url from public.profiles where is_active $$;

grant execute on function public.directory() to authenticated;

create or replace function public.is_active_profile(target_id uuid)
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = target_id and is_active) $$;

-- Lets any signed-in user rename themselves and set their own avatar without
-- granting a general self-update policy on profiles (which would also open
-- role/lead_id/is_active to direct tampering). Only name and avatar_url are
-- ever touched, and only for the caller's own row.
create or replace function public.update_own_profile(new_name text, new_avatar_url text)
returns public.profiles
language plpgsql security definer set search_path = public
as $$
declare
  updated public.profiles;
begin
  if new_name is null or trim(new_name) = '' then
    raise exception 'Name is required.';
  end if;

  update public.profiles
  set name = trim(new_name),
      avatar_url = new_avatar_url,
      updated_at = now()
  where id = auth.uid()
  returning * into updated;

  return updated;
end;
$$;

grant execute on function public.update_own_profile(text, text) to authenticated;

-- RLS is row-level only, so a lead permitted to update their attached
-- contributor's row could otherwise still smuggle a role change through.
-- This column-level guard blocks that regardless of which policy allowed
-- the row through. is_admin() checks auth.uid(), so this only applies to
-- requests made with a real user session — service-role calls (e.g. the
-- manage-user function) are unaffected since they don't change role via
-- UPDATE against an existing different value.
create or replace function public.prevent_non_admin_role_change()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if new.role is distinct from old.role and not public.is_admin() then
    raise exception 'Only admins can change a user''s role.';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_prevent_non_admin_role_change on public.profiles;
create trigger profiles_prevent_non_admin_role_change
  before update on public.profiles
  for each row execute procedure public.prevent_non_admin_role_change();

-- A project may have multiple leads (see public.project_leads); this checks
-- whether the caller is one of them.
create or replace function public.is_project_lead(target_project_id bigint)
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.project_leads where project_id = target_project_id and lead_id = auth.uid()) $$;

-- Messages allow two kinds of update: the recipient marking read_at, and
-- either side hiding the message from their own view ("delete for me").
-- Column-level RLS doesn't exist, so this guard blocks anything else —
-- editing body/sender/recipient, or one side flipping the other's flag.
create or replace function public.prevent_message_tampering()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if new.body is distinct from old.body
    or new.sender_id is distinct from old.sender_id
    or new.recipient_id is distinct from old.recipient_id
    or new.created_at is distinct from old.created_at
  then
    raise exception 'Messages cannot be edited.';
  end if;

  if new.read_at is distinct from old.read_at and auth.uid() <> old.recipient_id then
    raise exception 'Only the recipient can mark a message read.';
  end if;

  if new.deleted_by_sender is distinct from old.deleted_by_sender and auth.uid() <> old.sender_id then
    raise exception 'Only the sender can delete their own copy of a message.';
  end if;

  if new.deleted_by_recipient is distinct from old.deleted_by_recipient and auth.uid() <> old.recipient_id then
    raise exception 'Only the recipient can delete their own copy of a message.';
  end if;

  return new;
end;
$$;

drop trigger if exists messages_prevent_tampering on public.messages;
create trigger messages_prevent_tampering
  before update on public.messages
  for each row execute procedure public.prevent_message_tampering();

-- Lets a signed-in user stamp their own presence without granting general
-- update rights on profiles (only managers can update profiles otherwise).
create or replace function public.touch_presence()
returns void language sql security definer set search_path = public
as $$ update public.profiles set last_seen_at = now() where id = auth.uid() $$;

grant execute on function public.touch_presence() to authenticated;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name, email, role)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)), new.email, coalesce(new.raw_user_meta_data ->> 'role', 'contributor'))
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.activity_logs enable row level security;
alter table public.projects enable row level security;
alter table public.project_leads enable row level security;
alter table public.contributor_project_levels enable row level security;
alter table public.task_submissions enable row level security;
alter table public.weekly_targets enable row level security;
alter table public.resources enable row level security;
alter table public.house_rules enable row level security;
alter table public.messages enable row level security;

-- Admins see every profile; a lead sees only their own row plus contributors
-- attached to them (lead_id = their id); a contributor sees only their own row.
drop policy if exists "profiles read own or manager" on public.profiles;
create policy "profiles read own or manager" on public.profiles for select
  using (public.is_admin() or public.is_own_or_attached(id));
create policy "users create own profile" on public.profiles for insert with check (id = auth.uid() and role = 'contributor');
drop policy if exists "profiles managers update" on public.profiles;
create policy "profiles managers update" on public.profiles for update
  using (public.is_admin() or (public.is_manager() and public.is_own_or_attached(id)))
  with check (public.is_admin() or (public.is_manager() and public.is_own_or_attached(id)));

create policy "managers read activity logs" on public.activity_logs for select using (public.is_manager());
create policy "users log own auth events" on public.activity_logs for insert to authenticated
  with check (user_id = auth.uid() and event in ('login', 'logout'));
-- Failed sign-in attempts happen before a session exists, so they come in
-- unauthenticated (anon) and are restricted to that one event type with no user_id.
create policy "anon logs failed logins" on public.activity_logs for insert to anon
  with check (user_id is null and event = 'login_failed');

create policy "active users read projects" on public.projects for select using (public.is_active_user());
-- Admin creates and owns the master project list; a lead may only rename or
-- delete a project they're assigned to via project_leads — assignment
-- itself is admin-only (see "admins manage project leads" below).
drop policy if exists "managers manage projects" on public.projects;
drop policy if exists "admins or assigned lead update projects" on public.projects;
drop policy if exists "admins or assigned lead delete projects" on public.projects;
create policy "admins create projects" on public.projects for insert
  with check (public.is_admin());
create policy "admins or assigned lead update projects" on public.projects for update
  using (public.is_admin() or public.is_project_lead(id))
  with check (public.is_admin() or public.is_project_lead(id));
create policy "admins or assigned lead delete projects" on public.projects for delete
  using (public.is_admin() or public.is_project_lead(id));

-- Anyone can see who leads a project; only admins may assign/unassign leads.
create policy "active users read project leads" on public.project_leads for select
  using (public.is_active_user());
create policy "admins manage project leads" on public.project_leads for all
  using (public.is_admin()) with check (public.is_admin());

-- A contributor (or their lead) can read their own per-project levels; an
-- admin reads all. Writing is scoped further: only the lead who actually
-- runs that project (or an admin) may set a level for their own attached
-- contributor on it.
drop policy if exists "users read permitted project levels" on public.contributor_project_levels;
create policy "users read permitted project levels" on public.contributor_project_levels for select
  using (public.is_admin() or public.is_own_or_attached(user_id));
drop policy if exists "leads insert attached contributor project levels" on public.contributor_project_levels;
create policy "leads insert attached contributor project levels" on public.contributor_project_levels for insert
  with check (public.is_admin() or (public.is_own_or_attached(user_id) and public.is_project_lead(project_id)));
drop policy if exists "leads update attached contributor project levels" on public.contributor_project_levels;
create policy "leads update attached contributor project levels" on public.contributor_project_levels for update
  using (public.is_admin() or (public.is_own_or_attached(user_id) and public.is_project_lead(project_id)))
  with check (public.is_admin() or (public.is_own_or_attached(user_id) and public.is_project_lead(project_id)));
drop policy if exists "leads delete attached contributor project levels" on public.contributor_project_levels;
create policy "leads delete attached contributor project levels" on public.contributor_project_levels for delete
  using (public.is_admin() or (public.is_own_or_attached(user_id) and public.is_project_lead(project_id)));

create policy "active users read resources" on public.resources for select using (public.is_active_user());
create policy "managers manage resources" on public.resources for all using (public.is_manager()) with check (public.is_manager());
create policy "active users read rules" on public.house_rules for select using (public.is_active_user());
create policy "managers manage rules" on public.house_rules for all using (public.is_manager()) with check (public.is_manager());

-- A lead only reads/writes submissions belonging to their attached contributors
-- (or their own); an admin reads/writes all; a contributor reads/writes their own.
drop policy if exists "users read permitted submissions" on public.task_submissions;
create policy "users read permitted submissions" on public.task_submissions for select
  using (public.is_admin() or public.is_own_or_attached(user_id));
drop policy if exists "users create own submissions" on public.task_submissions;
create policy "users create own submissions" on public.task_submissions for insert
  with check (public.is_admin() or public.is_own_or_attached(user_id));
drop policy if exists "users update permitted submissions" on public.task_submissions;
create policy "users update permitted submissions" on public.task_submissions for update
  using (public.is_admin() or public.is_own_or_attached(user_id))
  with check (public.is_admin() or public.is_own_or_attached(user_id));
drop policy if exists "users delete permitted submissions" on public.task_submissions;
create policy "users delete permitted submissions" on public.task_submissions for delete
  using (public.is_admin() or public.is_own_or_attached(user_id));

drop policy if exists "users read own targets" on public.weekly_targets;
create policy "users read own targets" on public.weekly_targets for select
  using (public.is_admin() or public.is_own_or_attached(user_id));
drop policy if exists "managers manage targets" on public.weekly_targets;
create policy "managers manage targets" on public.weekly_targets for all
  using (public.is_admin() or public.is_own_or_attached(user_id))
  with check (public.is_admin() or public.is_own_or_attached(user_id));

-- Messaging is open to any two active users, independent of lead attachment.
create policy "users read own messages" on public.messages for select
  using (sender_id = auth.uid() or recipient_id = auth.uid());
create policy "active users send messages" on public.messages for insert
  with check (sender_id = auth.uid() and public.is_active_user() and public.is_active_profile(recipient_id));
create policy "recipients mark messages read" on public.messages for update
  using (recipient_id = auth.uid())
  with check (recipient_id = auth.uid());
-- Lets a sender flip their own deleted_by_sender flag; the trigger above
-- still blocks them from touching anything else, including the recipient's flag.
create policy "senders update own messages" on public.messages for update
  using (sender_id = auth.uid())
  with check (sender_id = auth.uid());

insert into storage.buckets (id, name, public)
values ('resources', 'resources', true)
on conflict (id) do nothing;

create policy "active users read resource files" on storage.objects for select
  using (bucket_id = 'resources' and public.is_active_user());
create policy "managers upload resource files" on storage.objects for insert
  with check (bucket_id = 'resources' and public.is_manager());
create policy "managers update resource files" on storage.objects for update
  using (bucket_id = 'resources' and public.is_manager()) with check (bucket_id = 'resources' and public.is_manager());
create policy "managers delete resource files" on storage.objects for delete
  using (bucket_id = 'resources' and public.is_manager());

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

-- Objects live at "<user id>/<filename>"; (storage.foldername(name))[1] is
-- that first path segment, so each user may only write inside their own folder.
create policy "active users read avatar files" on storage.objects for select
  using (bucket_id = 'avatars' and public.is_active_user());
create policy "users upload own avatar" on storage.objects for insert
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users update own avatar" on storage.objects for update
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users delete own avatar" on storage.objects for delete
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

-- Enables live INSERT/UPDATE notifications on task_submissions (e.g. the
-- "a contributor just submitted" toast). Realtime respects the table's RLS
-- select policy, so a manager receives every row's changes while a
-- contributor only receives changes to rows where user_id = auth.uid().
alter publication supabase_realtime add table public.task_submissions;

-- Enables live message delivery; RLS limits each viewer's stream to messages
-- where they are the sender or recipient.
alter publication supabase_realtime add table public.messages;