create extension if not exists pgcrypto;
-- Needed to schedule the daily-digest edge function (see the cron.schedule
-- snippet in the daily-digest deployment notes, run separately since it
-- embeds the project's service role key).
create extension if not exists pg_cron;
create extension if not exists pg_net;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text unique not null,
  role text not null default 'contributor' check (role in ('contributor', 'lead', 'admin')),
  shift text,
  meet_link text,
  is_active boolean not null default true,
  last_seen_at timestamptz,
  lead_id uuid references public.profiles(id) on delete set null,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- profiles already exists in production, so create table above is a no-op there;
-- this is what actually adds the columns to the live database.
alter table public.profiles add column if not exists last_seen_at timestamptz;
alter table public.profiles add column if not exists lead_id uuid references public.profiles(id) on delete set null;
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists must_change_password boolean not null default false;
-- A CB's own Remotasks worker ID (distinct from hiring_applications.remotasks_id, which only
-- exists for accounts created through the Hiring flow) — self-set from Edit Profile, and the
-- source of truth the extension-request prefill uses.
alter table public.profiles add column if not exists remotasks_id text check (char_length(remotasks_id) between 1 and 200);
-- Marks the FAQ bot's own profile row (role stays 'admin', so it's naturally excluded from
-- leaderboard()/contributor-only queries) so the messaging UI can badge it and the
-- bot_auto_reply() trigger below can find it without a hardcoded id.
alter table public.profiles add column if not exists is_bot boolean not null default false;
-- A short self-written line shown on the profile page — self-set from Edit Profile, same as
-- remotasks_id above. Exposed through contributor_public_stats() too, so it's visible even on a
-- peer's profile, not just your own team's.
alter table public.profiles add column if not exists bio text check (char_length(bio) <= 240);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  email text,
  event text not null check (event in ('login', 'login_failed', 'logout')),
  user_agent text,
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text unique not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- A project may have more than one lead, so assignment lives in its own
-- join table rather than a single lead_id column on projects.
create table if not exists public.project_leads (
  project_id bigint not null references public.projects(id) on delete cascade,
  lead_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (project_id, lead_id)
);

-- A contributor's rank is scored per project, not globally: a project has
-- its own contributor/l0/l1/l10 tiers, and the same person can hold a
-- different tier on each project they work on.
create table if not exists public.contributor_project_levels (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  level text not null default 'contributor' check (level in ('contributor', 'l0', 'l1', 'l10')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, project_id)
);

create table if not exists public.task_submissions (
  id bigint generated by default as identity primary key,
  task_id text,
  cb_email text not null,
  user_id uuid references public.profiles(id) on delete set null,
  project_id bigint references public.projects(id) on delete set null,
  stage text not null default 'attempt' check (stage in ('attempt', 'l0', 'l1')),
  status text not null default 'in_progress' check (status in ('submitted', 'in_progress', 'empty', 'expired', 'claimed_by_another')),
  notes text,
  date date,
  submitted_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- task_submissions already exists in production, so add the column here too.
alter table public.task_submissions add column if not exists snipboard_url text;
alter table public.task_submissions add column if not exists cts_submitted_at timestamptz;

-- A contributor asking their lead for more time before a submission is marked expired. Kept as
-- its own table (not a column on task_submissions) so the history of requests and how they were
-- resolved survives even after the submission itself later changes status.
create table if not exists public.task_extension_requests (
  id bigint generated by default as identity primary key,
  task_submission_id bigint not null references public.task_submissions(id) on delete cascade,
  requested_by uuid not null references public.profiles(id) on delete cascade,
  reason text check (char_length(reason) <= 500),
  status text not null default 'pending' check (status in ('pending', 'approved', 'denied')),
  requested_at timestamptz not null default now(),
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz
);

-- task_extension_requests already exists in production under that name — renamed here to
-- task_requests since it now holds more than just extension requests (see `type` below).
alter table if exists public.task_extension_requests rename to task_requests;

-- 'extension': a contributor asking their lead for more time (the table's original purpose).
-- 'bad_video': a lead/admin flagging a claimed task's video as bad, needing validation/removal
-- (ALOHA | URSA | YAM QA flow) — same pending/approved/denied lifecycle, different reviewer rules
-- (see the "users create extension or bad video requests" and "managers review requests" policies
-- below) and its own set of fields, added here as columns left null for 'extension' rows rather
-- than a second table, so both types share one review UI.
alter table public.task_requests add column if not exists type text not null default 'extension'
  check (type in ('extension', 'bad_video'));
alter table public.task_requests add column if not exists bad_video_category text;
alter table public.task_requests add column if not exists bad_video_frame text;
alter table public.task_requests add column if not exists bad_video_workforce text
  check (bad_video_workforce in ('REMOTE', 'ONSITE'));
alter table public.task_requests add column if not exists bad_video_workforce_name text;

-- Only one open request per submission *per type* at a time — resolve (or withdraw) the current
-- one before asking again. Scoped by type (not just submission) so a pending extension request
-- doesn't block a pending bad-video report on the same submission, or vice versa.
drop index if exists task_extension_requests_one_pending;
create unique index if not exists task_requests_one_pending_per_type
  on public.task_requests(task_submission_id, type) where status = 'pending';

create table if not exists public.weekly_targets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  week_start date not null,
  target integer not null default 50,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, week_start)
);

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  category text not null,
  title text not null,
  url text not null,
  project_id bigint references public.projects(id) on delete set null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) > 0),
  read_at timestamptz,
  -- Deletion is per-viewer ("delete for me"): each side can hide a message
  -- from their own view without removing it for the other person.
  deleted_by_sender boolean not null default false,
  deleted_by_recipient boolean not null default false,
  created_at timestamptz not null default now()
);

-- Reference content the FAQ bot's Groq-powered replies are grounded in — the bot-reply edge
-- function reads every row here and feeds only the ones whose `keywords` match the incoming
-- question into the model's system prompt (see selectReference() in
-- supabase/functions/bot-reply/index.ts), rather than joining every row unconditionally, so a
-- future large reference doc doesn't balloon every prompt regardless of relevance. Editable by SQL
-- for now — no admin UI yet.
create table if not exists public.bot_faqs (
  id bigint generated by default as identity primary key,
  keywords text[] not null,
  answer text not null,
  sort_order integer not null default 0
);

-- Seeds only when the table is empty, so re-running this script never duplicates rows or clobbers
-- edits made after the initial seed.
insert into public.bot_faqs (keywords, answer, sort_order)
select * from (values
  (array['extension', 'more time', 'deadline', 'expired'],
   'To ask for more time on a task before it expires, open Task Log, click the ⋮ menu on that row, and choose "Request extension." Your lead or an admin reviews it from there.', 1),
  (array['bad video', 'video removal', 'flag video', 'bad video report'],
   'To flag a claimed task''s video as bad, open Task Log, click the ⋮ menu on that row, and choose "Report bad video" (same-day tasks only). Your lead or an admin will review it.', 2),
  (array['cts', 'cts form', 'cts status'],
   'The CTS Form button on Task Log lets you submit your completed tasks for CTS — pick the submissions to include and it opens the form prefilled.', 3),
  (array['bulk import', 'import tasks', 'csv'],
   'Bulk Import on Task Log lets you paste multiple submissions at once (Date, Task ID, Status, Stage, Notes, Date Submitted, Project, Screenshot URL, tab-separated) instead of adding them one by one.', 4),
  (array['requests page', 'my requests', 'pending request'],
   'The Requests page in the left sidebar lists every extension request and bad video report — yours if you''re a contributor, your team''s if you''re a lead or admin.', 5),
  (array['disabled', 'account disabled', 'cant log in', 'login issue'],
   'If your account was disabled, message your lead or an admin directly — they can re-enable it from the Users page.', 6),
  (array['lead', 'who is my lead', 'contact lead'],
   'You can see and message your lead from your profile page, or from the online users list in the bottom-right corner if they''re currently online.', 7),
  (array['help', 'hi', 'hello'],
   'Hi! I''m Meera. I can help with: extension requests, bad video reports, the CTS form, bulk import, and general navigation. What do you need?', 8)
) as seed(keywords, answer, sort_order)
where not exists (select 1 from public.bot_faqs);

create index if not exists task_submissions_user_id_idx on public.task_submissions(user_id);
create index if not exists task_submissions_cb_email_idx on public.task_submissions(cb_email);
create index if not exists task_submissions_date_idx on public.task_submissions(date);
-- Enforces one row per Task ID; multiple NULLs are still allowed since a
-- unique index treats each NULL as distinct.
create unique index if not exists task_submissions_task_id_key on public.task_submissions(task_id);
create index if not exists resources_project_category_idx on public.resources(project_id, category, sort_order);
create index if not exists activity_logs_created_at_idx on public.activity_logs(created_at desc);
create index if not exists activity_logs_user_id_idx on public.activity_logs(user_id);
create index if not exists profiles_lead_id_idx on public.profiles(lead_id);
create index if not exists contributor_project_levels_user_idx on public.contributor_project_levels(user_id);
create index if not exists contributor_project_levels_project_idx on public.contributor_project_levels(project_id);
create index if not exists messages_sender_idx on public.messages(sender_id, created_at);
create index if not exists messages_recipient_idx on public.messages(recipient_id, created_at);
-- Names kept from before the task_extension_requests -> task_requests rename above; both now
-- index the shared table, covering extension and bad_video rows alike.
create index if not exists task_extension_requests_submission_idx on public.task_requests(task_submission_id);
create index if not exists task_extension_requests_requested_by_idx on public.task_requests(requested_by, status);

create or replace function public.is_active_user()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and is_active) $$;

create or replace function public.is_manager()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and is_active and role in ('lead', 'admin')) $$;

-- Admins manage everyone; leads are scoped to their attached contributors
-- (see is_own_or_attached below) rather than the whole roster.
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and is_active and role = 'admin') $$;

-- True when profile_id is the caller's own id, or a contributor whose
-- lead_id points back at the caller. Used both for a profiles row (by its
-- id) and for a task_submissions/weekly_targets row (by its user_id).
create or replace function public.is_own_or_attached(profile_id uuid)
returns boolean language sql stable security definer set search_path = public
as $$
  select profile_id = auth.uid()
    or exists (select 1 from public.profiles where id = profile_id and lead_id = auth.uid())
$$;

-- Messaging needs names and avatars for the people in a conversation, which the profiles table's
-- (deliberately) scoped read policy can't give a contributor, so it has its own RLS-independent
-- lookup. This function is callable by every signed-in user, so it must not list everyone to
-- everyone: admins and leads get every active user (with email and last_seen_at); a contributor
-- gets only the bot, the admins, their own lead, people they already exchanged messages with, and
-- whoever is online right now (for the online bubbles). A contributor never gets anyone's email,
-- and last_seen_at only for people online now — the 3 minutes matches ONLINE_THRESHOLD_MS in
-- src/lib/presence.ts.
-- role is included so the Dashboard's "Message admin" link can find an admin to message. is_bot
-- lets the messaging UI badge the FAQ bot. email lets the conversation-info panel link straight to
-- /contributors/:email.
-- Dropped first since CREATE OR REPLACE can't change a function's return type
-- (this one gained avatar_url after its first release, then role, then is_bot, then email).
drop function if exists public.directory();
create function public.directory()
returns table (id uuid, name text, is_active boolean, last_seen_at timestamptz, avatar_url text, role text, is_bot boolean, email text)
language sql stable security definer set search_path = public
as $$
  select p.id, p.name, p.is_active,
    case when public.is_manager() or p.last_seen_at > now() - interval '3 minutes' then p.last_seen_at end,
    p.avatar_url, p.role, p.is_bot,
    case when public.is_manager() then p.email end
  from public.profiles p
  where p.is_active and (
    public.is_manager()
    or p.is_bot
    or p.role = 'admin'
    or p.last_seen_at > now() - interval '3 minutes'
    or p.id = (select me.lead_id from public.profiles me where me.id = auth.uid())
    or exists (
      select 1 from public.messages m
      where (m.sender_id = auth.uid() and m.recipient_id = p.id)
         or (m.recipient_id = auth.uid() and m.sender_id = p.id)
    )
  )
$$;

grant execute on function public.directory() to authenticated;

-- Who has a desk or office on the caller's floor(s) of the Office page. Each lead's team has its own
-- floor (the lead's private office + their contributors' desks); contributors with no lead share
-- one; admins who don't lead a team have an admin floor. Everyone looking at a floor has to get the
-- same list, because the floor plan is built from it and positions are shared as floor-plan
-- coordinates — directory() can't be used, since what it returns depends on who's online and who
-- you've messaged. Scoped like the rest of the app: a contributor gets their lead and teammates, a
-- lead gets their own team, an admin gets everyone (to visit any floor). Only what the office draws:
-- no email, no last seen (online status still comes from directory()).
drop function if exists public.office_roster();
create function public.office_roster()
returns table (id uuid, name text, role text, avatar_url text, lead_id uuid)
language sql stable security definer set search_path = public
as $$
  select p.id, p.name, p.role, p.avatar_url, p.lead_id
  from public.profiles p, public.profiles me
  where me.id = auth.uid()
    and p.is_active and not p.is_bot
    and (
      public.is_admin()
      or p.id = me.id
      or p.id = me.lead_id
      or p.lead_id = me.id
      or (me.role = 'contributor' and p.role = 'contributor' and p.lead_id is not distinct from me.lead_id)
    )
$$;

grant execute on function public.office_roster() to authenticated;

-- One row per conversation: the unread count and the last 5 messages (oldest first), so the inbox
-- list, unread badge, bot reveal timing and notification sound never need a whole thread. Full
-- threads are fetched a page at a time when a chat is opened. Messages the caller deleted for
-- themselves are left out. Runs as the caller, so the messages read policy still applies.
create or replace function public.conversation_summaries()
returns table (other_user_id uuid, unread_count bigint, recent jsonb)
language sql stable set search_path = public
as $$
  with mine as (
    select m.*, case when m.sender_id = auth.uid() then m.recipient_id else m.sender_id end as other_id
    from public.messages m
    where (m.sender_id = auth.uid() and not m.deleted_by_sender)
       or (m.recipient_id = auth.uid() and not m.deleted_by_recipient)
  )
  select o.other_id,
    count(*) filter (where o.recipient_id = auth.uid() and o.read_at is null),
    (select jsonb_agg(to_jsonb(x) - 'other_id' order by x.id)
       from (select * from mine mm where mm.other_id = o.other_id order by mm.id desc limit 5) x)
  from mine o
  group by o.other_id
$$;

grant execute on function public.conversation_summaries() to authenticated;

-- Ranks a contributor's own teammates (same lead_id) by tasks submitted in a date range, which
-- the scoped "profiles read own or manager" policy can't do on its own — same rationale as
-- directory() above, but counting submissions instead of listing presence, and scoped to one
-- team instead of everyone. Two contributors both without a lead (lead_id is null) are still
-- teammates of each other. Matches a submission to its contributor by user_id OR cb_email
-- (case-insensitive), same as the dashboard summary, since a submission logged for someone else
-- by their lead/admin carries that contributor's cb_email but the logger's user_id.
drop function if exists public.leaderboard(date, date);
create function public.leaderboard(range_start date, range_end date)
returns table (user_id uuid, name text, avatar_url text, cb_email text, tasks_submitted bigint)
language sql stable security definer set search_path = public
as $$
  select
    p.id as user_id,
    p.name,
    p.avatar_url,
    p.email as cb_email,
    (
      select count(*) from public.task_submissions s
      where s.status = 'submitted'
        and s.date >= range_start
        and s.date <= range_end
        and (s.user_id = p.id or lower(s.cb_email) = lower(p.email))
    ) as tasks_submitted
  from public.profiles p
  where p.role = 'contributor' and p.is_active
    and p.lead_id is not distinct from (select lead_id from public.profiles where id = auth.uid())
  order by tasks_submitted desc, p.name asc
$$;

grant execute on function public.leaderboard(date, date) to authenticated;

-- Lets any active user open a peer contributor's profile and see their
-- identity plus aggregate progress (goal, 30-day trend, stage/project
-- breakdown, project levels) — same rationale as directory()/leaderboard()
-- above. The scoped "users read permitted submissions"/"users read
-- permitted project levels" policies still govern everything this
-- deliberately leaves out: task IDs, diff-viewer links, per-row status,
-- and editing — those stay restricted to the owner, their lead, or an admin.
drop function if exists public.contributor_public_stats(text, date);
create function public.contributor_public_stats(p_target_email text, p_week_start date)
returns table (
  id uuid,
  name text,
  avatar_url text,
  role text,
  lead_id uuid,
  is_active boolean,
  shift text,
  bio text,
  weekly_target integer,
  submitted_this_week bigint,
  stage_breakdown jsonb,
  project_breakdown jsonb,
  trend jsonb,
  levels jsonb
)
language sql stable security definer set search_path = public
as $$
  with target as (
    select * from public.profiles p where lower(p.email) = lower(p_target_email) and p.role = 'contributor'
  ),
  target_submissions as (
    select s.* from public.task_submissions s, target t
    where lower(s.cb_email) = lower(t.email) or s.user_id = t.id
  ),
  stage_agg as (
    select coalesce(jsonb_object_agg(stage, cnt), '{}'::jsonb) as j
    from (select stage, count(*) as cnt from target_submissions group by stage) x
  ),
  project_agg as (
    select coalesce(jsonb_agg(jsonb_build_object('name', pname, 'total', cnt) order by cnt desc), '[]'::jsonb) as j
    from (
      select coalesce(p.name, 'Unassigned') as pname, count(*) as cnt
      from target_submissions ts
      left join public.projects p on p.id = ts.project_id
      group by coalesce(p.name, 'Unassigned')
    ) x
  ),
  trend_days as (
    select gs::date as d from generate_series(current_date - interval '29 days', current_date, interval '1 day') gs
  ),
  trend_agg as (
    select coalesce(
      jsonb_agg(jsonb_build_object('date', to_char(td.d, 'YYYY-MM-DD'), 'value', coalesce(c.cnt, 0)) order by td.d),
      '[]'::jsonb
    ) as j
    from trend_days td
    left join (
      select date as d, count(*) as cnt from target_submissions where status = 'submitted' group by date
    ) c on c.d = td.d
  ),
  levels_agg as (
    select coalesce(
      jsonb_agg(jsonb_build_object('project_id', cpl.project_id, 'level', cpl.level)),
      '[]'::jsonb
    ) as j
    from public.contributor_project_levels cpl, target t
    where cpl.user_id = t.id
  )
  select
    t.id,
    t.name,
    t.avatar_url,
    t.role,
    t.lead_id,
    t.is_active,
    t.shift,
    t.bio,
    coalesce((select wt.target from public.weekly_targets wt where wt.user_id = t.id and wt.week_start = p_week_start), 50) as weekly_target,
    (
      select count(*) from target_submissions ts
      where ts.status = 'submitted' and ts.date >= p_week_start and ts.date <= (p_week_start + 6)
    ) as submitted_this_week,
    (select j from stage_agg) as stage_breakdown,
    (select j from project_agg) as project_breakdown,
    (select j from trend_agg) as trend,
    (select j from levels_agg) as levels
  from target t
$$;

grant execute on function public.contributor_public_stats(text, date) to authenticated;

-- Same rollups looked up by user id, so a contributor can open a peer's profile without ever being
-- told that peer's email (directory() hides it). Returns nothing the email version doesn't.
create or replace function public.contributor_public_stats_by_id(p_target_id uuid, p_week_start date)
returns table(id uuid, name text, avatar_url text, role text, lead_id uuid, is_active boolean, shift text, bio text, weekly_target integer, submitted_this_week bigint, stage_breakdown jsonb, project_breakdown jsonb, trend jsonb, levels jsonb)
language sql stable security definer set search_path = public
as $$ select s.* from public.contributor_public_stats((select p.email from public.profiles p where p.id = p_target_id), p_week_start) s $$;

grant execute on function public.contributor_public_stats_by_id(uuid, date) to authenticated;

create or replace function public.is_active_profile(target_id uuid)
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = target_id and is_active) $$;

-- Lets any signed-in user rename themselves, set their own avatar, Remotasks worker ID, shift and
-- bio, without granting a general self-update policy on profiles (which would also open
-- role/lead_id/is_active to direct tampering). Only these fields are ever touched, and only for
-- the caller's own row. Dropped first since an earlier-arity version would otherwise stay
-- callable alongside this one as a separate overload.
drop function if exists public.update_own_profile(text, text);
drop function if exists public.update_own_profile(text, text, text);
create or replace function public.update_own_profile(
  new_name text,
  new_avatar_url text,
  new_remotasks_id text default null,
  new_shift text default null,
  new_bio text default null
)
returns public.profiles
language plpgsql security definer set search_path = public
as $$
declare
  updated public.profiles;
begin
  if new_name is null or trim(new_name) = '' then
    raise exception 'Name is required.';
  end if;

  update public.profiles
  set name = trim(new_name),
      avatar_url = new_avatar_url,
      remotasks_id = nullif(trim(coalesce(new_remotasks_id, '')), ''),
      shift = nullif(trim(coalesce(new_shift, '')), ''),
      bio = nullif(trim(coalesce(new_bio, '')), ''),
      updated_at = now()
  where id = auth.uid()
  returning * into updated;

  return updated;
end;
$$;

grant execute on function public.update_own_profile(text, text, text, text, text) to authenticated;

-- Called by a signed-in user right after they set their own new password,
-- so the forced-change gate (must_change_password) lifts for their own row
-- only. Never settable to true from the client — only manage-user (service
-- role) sets it, on account creation or an admin password reset.
create or replace function public.clear_must_change_password()
returns public.profiles
language plpgsql security definer set search_path = public
as $$
declare
  updated public.profiles;
begin
  update public.profiles
  set must_change_password = false,
      updated_at = now()
  where id = auth.uid()
  returning * into updated;

  return updated;
end;
$$;

grant execute on function public.clear_must_change_password() to authenticated;

-- RLS is row-level only, so a lead permitted to update their attached
-- contributor's row could otherwise still smuggle a role change through.
-- This column-level guard blocks that regardless of which policy allowed
-- the row through. is_admin() checks auth.uid(), so this only applies to
-- requests made with a real user session — service-role calls (e.g. the
-- manage-user function) are unaffected since they don't change role via
-- UPDATE against an existing different value.
create or replace function public.prevent_non_admin_role_change()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if new.role is distinct from old.role and not public.is_admin() then
    raise exception 'Only admins can change a user''s role.';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_prevent_non_admin_role_change on public.profiles;
create trigger profiles_prevent_non_admin_role_change
  before update on public.profiles
  for each row execute procedure public.prevent_non_admin_role_change();

-- A project may have multiple leads (see public.project_leads); this checks
-- whether the caller is one of them.
create or replace function public.is_project_lead(target_project_id bigint)
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.project_leads where project_id = target_project_id and lead_id = auth.uid()) $$;

-- Messages allow two kinds of update: the recipient marking read_at, and
-- either side hiding the message from their own view ("delete for me").
-- Column-level RLS doesn't exist, so this guard blocks anything else —
-- editing body/sender/recipient, or one side flipping the other's flag.
create or replace function public.prevent_message_tampering()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if new.body is distinct from old.body
    or new.sender_id is distinct from old.sender_id
    or new.recipient_id is distinct from old.recipient_id
    or new.created_at is distinct from old.created_at
  then
    raise exception 'Messages cannot be edited.';
  end if;

  if new.read_at is distinct from old.read_at and auth.uid() <> old.recipient_id then
    raise exception 'Only the recipient can mark a message read.';
  end if;

  if new.deleted_by_sender is distinct from old.deleted_by_sender and auth.uid() <> old.sender_id then
    raise exception 'Only the sender can delete their own copy of a message.';
  end if;

  if new.deleted_by_recipient is distinct from old.deleted_by_recipient and auth.uid() <> old.recipient_id then
    raise exception 'Only the recipient can delete their own copy of a message.';
  end if;

  return new;
end;
$$;

drop trigger if exists messages_prevent_tampering on public.messages;
create trigger messages_prevent_tampering
  before update on public.messages
  for each row execute procedure public.prevent_message_tampering();

-- Spam guard, enforced here so it holds however a message is sent (the UI is not the only client).
-- Every message to the FAQ bot costs a Groq call and produces a reply, so that is capped tighter:
-- 5 a minute to the bot, 30 a minute to people, and 2000 characters per message (the longest real
-- one so far is ~1150). Bots are exempt so the bot's own replies and the daily digest are never
-- blocked.
-- Over the limit to the bot, the message is dropped (returning null skips the row without aborting
-- the transaction, which is what lets the bot's reply be saved in the same statement) and the bot
-- posts a fixed reminder, at most one a minute so the warnings can't be spammed either. The other
-- two limits raise an exception, whose text the chat UI shows to the sender as-is.
create or replace function public.enforce_message_limits()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  warning constant text := 'Please be reminded: no spamming. You are sending messages too fast, so I could not take your last message. Give it a minute, then send it again.';
  sender_is_bot boolean;
  recipient_is_bot boolean;
  recent integer;
begin
  select is_bot into sender_is_bot from public.profiles where id = new.sender_id;
  if coalesce(sender_is_bot, false) then
    return new;
  end if;

  if char_length(new.body) > 2000 then
    raise exception 'Messages can be at most 2000 characters.';
  end if;

  select is_bot into recipient_is_bot from public.profiles where id = new.recipient_id;
  if coalesce(recipient_is_bot, false) then
    select count(*) into recent from public.messages
     where sender_id = new.sender_id and recipient_id = new.recipient_id and created_at > now() - interval '60 seconds';
    if recent >= 5 then
      if not exists (
        select 1 from public.messages
         where sender_id = new.recipient_id and recipient_id = new.sender_id and body = warning
           and created_at > now() - interval '60 seconds'
      ) then
        insert into public.messages (sender_id, recipient_id, body) values (new.recipient_id, new.sender_id, warning);
      end if;
      return null;
    end if;
  else
    select count(*) into recent from public.messages
     where sender_id = new.sender_id and created_at > now() - interval '60 seconds';
    if recent >= 30 then
      raise exception 'You are sending messages too fast. Please wait a moment.';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists messages_enforce_limits on public.messages;
create trigger messages_enforce_limits
  before insert on public.messages
  for each row execute function public.enforce_message_limits();

-- Lets a signed-in user stamp their own presence without granting general
-- update rights on profiles (only managers can update profiles otherwise).
create or replace function public.touch_presence()
returns void language sql security definer set search_path = public
as $$ update public.profiles set last_seen_at = now() where id = auth.uid() $$;

grant execute on function public.touch_presence() to authenticated;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name, email, role)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)), new.email, coalesce(new.raw_user_meta_data ->> 'role', 'contributor'))
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- Holds the two values bot_auto_reply() needs to call the bot-reply edge function: its URL, and a
-- dedicated shared secret (not the Supabase service role key — see the comment on
-- bot_auto_reply()'s webhook_secret) to authenticate as. `alter database ... set app.*` would be
-- the more usual way
-- to stash config like this for a plpgsql function to read via current_setting(), but Supabase's
-- hosted Postgres doesn't grant project accounts permission to set custom database parameters
-- (confirmed: "permission denied to set parameter" on that approach) — this table is the
-- workaround. RLS is enabled with deliberately zero policies, so every role reaches it only via a
-- security definer function (which bypasses RLS), never directly through the API/PostgREST.
create table if not exists public.app_secrets (
  key text primary key,
  value text not null
);

-- Auto-replies on behalf of the FAQ bot. Can't call Groq synchronously from plpgsql, so this just
-- notifies the bot-reply edge function (via pg_net, fire-and-forget) with the new message; that
-- function reads bot_faqs itself for grounding, calls Groq, and inserts the reply message using its
-- own service-role client — see supabase/functions/bot-reply/index.ts.
-- security definer (same as handle_new_user above) so it can read app_secrets despite that table
-- having no policies, and so the two keys in it are set once via a separate, uncommitted insert (see
-- the deployment notes) rather than living in this file.
-- bot_webhook_secret is a value we generated ourselves, not a real Supabase credential — it exists
-- only so bot-reply can tell this trigger apart from an arbitrary caller. Because it isn't a real
-- JWT, the bot-reply function must be deployed with `supabase functions deploy bot-reply
-- --no-verify-jwt`, or Supabase's platform gateway rejects the request before bot-reply's own code
-- (which checks this same secret) ever runs.
create or replace function public.bot_auto_reply()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  bot_id uuid := (select id from public.profiles where is_bot limit 1);
  reply_url text := (select value from public.app_secrets where key = 'bot_reply_url');
  -- A dedicated secret for this one handshake, not the Supabase service role key — see the comment
  -- on the same check in supabase/functions/bot-reply/index.ts for why.
  webhook_secret text := (select value from public.app_secrets where key = 'bot_webhook_secret');
begin
  if bot_id is null or new.recipient_id is distinct from bot_id or new.sender_id = bot_id then
    return new;
  end if;
  if reply_url is null or webhook_secret is null then
    return new;
  end if;
  perform net.http_post(
    url := reply_url,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || webhook_secret
    ),
    body := jsonb_build_object(
      'message_id', new.id, 'sender_id', new.sender_id, 'recipient_id', new.recipient_id, 'body', new.body
    )
  );
  return new;
end;
$$;

drop trigger if exists on_message_to_bot on public.messages;
create trigger on_message_to_bot after insert on public.messages
for each row execute procedure public.bot_auto_reply();

alter table public.profiles enable row level security;
alter table public.activity_logs enable row level security;
alter table public.projects enable row level security;
alter table public.project_leads enable row level security;
alter table public.contributor_project_levels enable row level security;
alter table public.task_submissions enable row level security;
alter table public.task_requests enable row level security;
alter table public.weekly_targets enable row level security;
alter table public.resources enable row level security;
alter table public.messages enable row level security;
alter table public.bot_faqs enable row level security;
-- bot_faqs' policies (signed-in users read, admins manage) are defined further down with the rest.
alter table public.app_secrets enable row level security;

-- Admins see every profile; a lead sees only their own row plus contributors
-- attached to them (lead_id = their id); a contributor sees only their own row.
drop policy if exists "profiles read own or manager" on public.profiles;
create policy "profiles read own or manager" on public.profiles for select
  using (public.is_admin() or public.is_own_or_attached(id));
create policy "users create own profile" on public.profiles for insert with check (id = auth.uid() and role = 'contributor');
drop policy if exists "profiles managers update" on public.profiles;
create policy "profiles managers update" on public.profiles for update
  using (public.is_admin() or (public.is_manager() and public.is_own_or_attached(id)))
  with check (public.is_admin() or (public.is_manager() and public.is_own_or_attached(id)));

create policy "managers read activity logs" on public.activity_logs for select using (public.is_manager());
create policy "users log own auth events" on public.activity_logs for insert to authenticated
  with check (user_id = auth.uid() and event in ('login', 'logout'));
-- Failed sign-in attempts happen before a session exists, so they come in
-- unauthenticated (anon) and are restricted to that one event type with no user_id.
create policy "anon logs failed logins" on public.activity_logs for insert to anon
  with check (user_id is null and event = 'login_failed');
-- The Activity Log page's "Clear log" is admin-only at the route level; this
-- mirrors that so the delete isn't silently dropped by RLS.
create policy "admins clear activity logs" on public.activity_logs for delete
  using (public.is_admin());

-- Same visibility model as the resources read policy below: admins see every project, a lead sees
-- the ones they're assigned to, and a contributor sees the ones their lead is assigned to. A
-- project with no lead assigned yet is visible to admins only.
drop policy if exists "active users read projects" on public.projects;
drop policy if exists "users read assigned projects" on public.projects;
create policy "users read assigned projects" on public.projects for select using (
  public.is_active_user() and (
    public.is_admin()
    or public.is_project_lead(id)
    or exists (
      select 1 from public.profiles p join public.project_leads pl on pl.lead_id = p.lead_id
      where p.id = auth.uid() and pl.project_id = projects.id
    )
  )
);
-- Admin creates and owns the master project list; a lead may only rename or
-- delete a project they're assigned to via project_leads — assignment
-- itself is admin-only (see "admins manage project leads" below).
drop policy if exists "managers manage projects" on public.projects;
drop policy if exists "admins or assigned lead update projects" on public.projects;
drop policy if exists "admins or assigned lead delete projects" on public.projects;
create policy "admins create projects" on public.projects for insert
  with check (public.is_admin());
create policy "admins or assigned lead update projects" on public.projects for update
  using (public.is_admin() or public.is_project_lead(id))
  with check (public.is_admin() or public.is_project_lead(id));
create policy "admins or assigned lead delete projects" on public.projects for delete
  using (public.is_admin() or public.is_project_lead(id));

-- Anyone can see who leads a project; only admins may assign/unassign leads.
create policy "active users read project leads" on public.project_leads for select
  using (public.is_active_user());
create policy "admins manage project leads" on public.project_leads for all
  using (public.is_admin()) with check (public.is_admin());

-- A contributor (or their lead) can read their own per-project levels; an
-- admin reads all. Writing is scoped further: only the lead who actually
-- runs that project (or an admin) may set a level for their own attached
-- contributor on it.
drop policy if exists "users read permitted project levels" on public.contributor_project_levels;
create policy "users read permitted project levels" on public.contributor_project_levels for select
  using (public.is_admin() or public.is_own_or_attached(user_id));
drop policy if exists "leads insert attached contributor project levels" on public.contributor_project_levels;
create policy "leads insert attached contributor project levels" on public.contributor_project_levels for insert
  with check (public.is_admin() or (public.is_own_or_attached(user_id) and public.is_project_lead(project_id)));
drop policy if exists "leads update attached contributor project levels" on public.contributor_project_levels;
create policy "leads update attached contributor project levels" on public.contributor_project_levels for update
  using (public.is_admin() or (public.is_own_or_attached(user_id) and public.is_project_lead(project_id)))
  with check (public.is_admin() or (public.is_own_or_attached(user_id) and public.is_project_lead(project_id)));
drop policy if exists "leads delete attached contributor project levels" on public.contributor_project_levels;
create policy "leads delete attached contributor project levels" on public.contributor_project_levels for delete
  using (public.is_admin() or (public.is_own_or_attached(user_id) and public.is_project_lead(project_id)));

-- Resources are per-project: a resource with no project (project_id is null) is general and stays
-- visible to everyone, same as before. A resource tied to a project is visible to that project's
-- lead(s), an admin, and any contributor whose own lead leads that project — not to every active
-- user the way it used to be.
drop policy if exists "active users read resources" on public.resources;
create policy "users read permitted resources" on public.resources for select
  using (
    public.is_admin()
    or project_id is null
    or public.is_project_lead(project_id)
    or exists (
      select 1 from public.profiles p
      join public.project_leads pl on pl.lead_id = p.lead_id
      where p.id = auth.uid() and pl.project_id = resources.project_id
    )
  );
-- An admin manages any resource. A lead may only create/edit/delete resources tied to a project
-- they actually lead — never a general (project_id is null) resource, that stays admin-only so
-- there's one deliberate "visible to everyone" bucket leads can't add to freely.
drop policy if exists "managers manage resources" on public.resources;
create policy "admins or project leads manage resources" on public.resources for all
  using (public.is_admin() or (project_id is not null and public.is_project_lead(project_id)))
  with check (public.is_admin() or (project_id is not null and public.is_project_lead(project_id)));

-- Read is harmless (it's just help text) and lets a future admin FAQ-management UI list existing
-- entries; the bot_auto_reply() trigger itself is security definer and doesn't need this policy at
-- all, since it bypasses RLS regardless.
create policy "active users read bot faqs" on public.bot_faqs for select using (public.is_active_user());
create policy "admins manage bot faqs" on public.bot_faqs for all using (public.is_admin()) with check (public.is_admin());

-- A lead only reads/writes submissions belonging to their attached contributors
-- (or their own); an admin reads/writes all; a contributor reads/writes their own.
drop policy if exists "users read permitted submissions" on public.task_submissions;
create policy "users read permitted submissions" on public.task_submissions for select
  using (public.is_admin() or public.is_own_or_attached(user_id));
drop policy if exists "users create own submissions" on public.task_submissions;
create policy "users create own submissions" on public.task_submissions for insert
  with check (public.is_admin() or public.is_own_or_attached(user_id));
drop policy if exists "users update permitted submissions" on public.task_submissions;
create policy "users update permitted submissions" on public.task_submissions for update
  using (public.is_admin() or public.is_own_or_attached(user_id))
  with check (public.is_admin() or public.is_own_or_attached(user_id));
drop policy if exists "users delete permitted submissions" on public.task_submissions;
create policy "users delete permitted submissions" on public.task_submissions for delete
  using (public.is_admin() or public.is_own_or_attached(user_id));

-- Extension: a contributor (or their lead) sees their own; an admin sees all. Bad video: also
-- visible to whoever owns/is-attached-to the *flagged task's* contributor, even though that
-- person isn't the requester (a manager flagging someone else's task is the normal case here).
drop policy if exists "users read permitted extension requests" on public.task_requests;
create policy "users read permitted requests" on public.task_requests for select
  using (
    public.is_admin()
    or public.is_own_or_attached(requested_by)
    or (type = 'bad_video' and exists (
      select 1 from public.task_submissions s
      where s.id = task_submission_id and public.is_own_or_attached(s.user_id)
    ))
  );
-- Extension: only for a submission the caller (or their attached contributor) actually owns.
-- Bad video: the CB is the first touch — they flag it on their own claimed task, same ownership
-- rule as extension — but a manager can also flag any task directly (e.g. spot-checking).
drop policy if exists "users create own extension requests" on public.task_requests;
create policy "users create extension or bad video requests" on public.task_requests for insert
  with check (
    requested_by = auth.uid()
    and (
      (type = 'extension' and exists (
        select 1 from public.task_submissions s
        where s.id = task_submission_id and public.is_own_or_attached(s.user_id)
      ))
      or (type = 'bad_video' and (
        public.is_manager()
        or exists (
          select 1 from public.task_submissions s
          where s.id = task_submission_id and public.is_own_or_attached(s.user_id)
        )
      ))
    )
  );
-- Extension: only the requester's lead (or admin) decides it — never the requester themselves,
-- since it's self-service. Bad video: any manager (including the one who filed it — filing the
-- external form themselves right after flagging it is the normal flow, not a rubber stamp).
drop policy if exists "leads review extension requests" on public.task_requests;
create policy "managers review requests" on public.task_requests for update
  using (
    public.is_admin()
    or (type = 'bad_video' and public.is_manager())
    or (type = 'extension' and public.is_manager() and public.is_own_or_attached(requested_by) and requested_by <> auth.uid())
  )
  with check (
    public.is_admin()
    or (type = 'bad_video' and public.is_manager())
    or (type = 'extension' and public.is_manager() and public.is_own_or_attached(requested_by) and requested_by <> auth.uid())
  );
-- The requester can withdraw their own pending request; a lead/admin can remove one any time
-- (any manager for bad_video, same reasoning as the review policy above).
drop policy if exists "users delete own or managed extension requests" on public.task_requests;
create policy "users delete own or managed requests" on public.task_requests for delete
  using (
    public.is_admin()
    or (public.is_manager() and (public.is_own_or_attached(requested_by) or type = 'bad_video'))
    or (requested_by = auth.uid() and status = 'pending')
  );

drop policy if exists "users read own targets" on public.weekly_targets;
create policy "users read own targets" on public.weekly_targets for select
  using (public.is_admin() or public.is_own_or_attached(user_id));
drop policy if exists "managers manage targets" on public.weekly_targets;
create policy "managers manage targets" on public.weekly_targets for all
  using (public.is_admin() or public.is_own_or_attached(user_id))
  with check (public.is_admin() or public.is_own_or_attached(user_id));

-- Messaging is open to any two active users, independent of lead attachment.
create policy "users read own messages" on public.messages for select
  using (sender_id = auth.uid() or recipient_id = auth.uid());
create policy "active users send messages" on public.messages for insert
  with check (sender_id = auth.uid() and public.is_active_user() and public.is_active_profile(recipient_id));
create policy "recipients mark messages read" on public.messages for update
  using (recipient_id = auth.uid())
  with check (recipient_id = auth.uid());
-- Lets a sender flip their own deleted_by_sender flag; the trigger above
-- still blocks them from touching anything else, including the recipient's flag.
create policy "senders update own messages" on public.messages for update
  using (sender_id = auth.uid())
  with check (sender_id = auth.uid());

insert into storage.buckets (id, name, public)
values ('resources', 'resources', true)
on conflict (id) do nothing;

create policy "active users read resource files" on storage.objects for select
  using (bucket_id = 'resources' and public.is_active_user());
create policy "managers upload resource files" on storage.objects for insert
  with check (bucket_id = 'resources' and public.is_manager());
create policy "managers update resource files" on storage.objects for update
  using (bucket_id = 'resources' and public.is_manager()) with check (bucket_id = 'resources' and public.is_manager());
create policy "managers delete resource files" on storage.objects for delete
  using (bucket_id = 'resources' and public.is_manager());

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

-- Objects live at "<user id>/<filename>"; (storage.foldername(name))[1] is
-- that first path segment, so each user may only write inside their own folder.
create policy "active users read avatar files" on storage.objects for select
  using (bucket_id = 'avatars' and public.is_active_user());
create policy "users upload own avatar" on storage.objects for insert
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users update own avatar" on storage.objects for update
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users delete own avatar" on storage.objects for delete
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

-- Enables live INSERT/UPDATE notifications on task_submissions (e.g. the
-- "a contributor just submitted" toast). Realtime respects the table's RLS
-- select policy, so a manager receives every row's changes while a
-- contributor only receives changes to rows where user_id = auth.uid().
alter publication supabase_realtime add table public.task_submissions;

-- Enables live message delivery; RLS limits each viewer's stream to messages
-- where they are the sender or recipient.
alter publication supabase_realtime add table public.messages;

-- Enables the notification bell's live "X requested an extension" / "X flagged a bad video"
-- alerts for leads/admins. Wrapped in a guard (unlike the two additions above) since
-- `alter publication ... add table` errors instead of no-op-ing if already added, and this
-- script gets re-run.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'task_requests'
  ) then
    alter publication supabase_realtime add table public.task_requests;
  end if;
end $$;
-- Hiring: each lead has a public application link (/apply/<lead id>). An
-- applicant fills in the form; the lead reviews the entry and accepts or
-- denies it. Accepting creates the applicant's login on that lead's team.
-- Each lead can switch their application link on or off. It defaults to on, so
-- a lead's link works as soon as it's shared; turning it off closes the form
-- without touching applications already received. A lead flips their own
-- value through the existing "profiles managers update" policy.
alter table public.profiles add column if not exists accepting_applications boolean not null default true;

create table if not exists public.hiring_applications (
  id bigint generated by default as identity primary key,
  lead_id uuid not null references public.profiles(id) on delete cascade,
  remotasks_email text not null check (char_length(remotasks_email) between 3 and 254),
  remotasks_id text not null check (char_length(remotasks_id) between 1 and 200),
  full_name text not null check (char_length(full_name) between 1 and 200),
  active_email text not null check (char_length(active_email) between 3 and 254),
  facebook_url text not null check (char_length(facebook_url) between 1 and 500),
  has_robotics_background boolean not null,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'denied')),
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  -- The login created for this applicant. Accepting doesn't create it: an accepted applicant
  -- gets an account in a separate step (manage-user, create-account), so this is null until then.
  user_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Step 2 of the form: the applicant's computer. All nullable: an application
-- received before this step existed stays valid, and the processor, graphics
-- card and GPU memory are optional questions that stay null when left blank.
-- submit_hiring_application() below requires the two yes/no answers.
alter table public.hiring_applications add column if not exists has_personal_computer boolean;
alter table public.hiring_applications add column if not exists has_stable_internet boolean;
alter table public.hiring_applications add column if not exists cpu text check (char_length(cpu) between 1 and 200);
alter table public.hiring_applications add column if not exists gpu text check (char_length(gpu) between 1 and 200);
alter table public.hiring_applications add column if not exists gpu_memory_gb numeric(5, 1) check (gpu_memory_gb >= 0 and gpu_memory_gb <= 256);

-- The profile answer used to have to be an https link. Applications brought over from the
-- old Google Form include answers that aren't (a name, "Nil"), so the table only limits the
-- length; submit_hiring_application() below still requires a real link from the public form,
-- and the Hiring page shows anything that isn't a link as plain text. This drops the old
-- check from a database created before this change (and re-adds the current one).
do $$
declare c record;
begin
  for c in
    select conname from pg_constraint
    where conrelid = 'public.hiring_applications'::regclass and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%facebook_url%'
  loop
    execute format('alter table public.hiring_applications drop constraint %I', c.conname);
  end loop;
  alter table public.hiring_applications
    add constraint hiring_applications_facebook_url_check check (char_length(facebook_url) between 1 and 500);
end $$;

-- When the applicant was last emailed, set by the manage-user function after a send.
alter table public.hiring_applications add column if not exists emailed_at timestamptz;

-- Whether an accepted applicant has completed onboarding (the bootcamp, in practice). This is
-- separate from having an account (user_id): a lead flips it from the Accepted tab, through the
-- manage-user edge function, once someone has actually gone through onboarding.
alter table public.hiring_applications add column if not exists onboarded_at timestamptz;

create index if not exists hiring_applications_lead_idx on public.hiring_applications(lead_id, status, created_at desc);
-- One live application per applicant per lead; a denied applicant may re-apply.
create unique index if not exists hiring_applications_open_key
  on public.hiring_applications(lead_id, lower(remotasks_email)) where status in ('pending', 'accepted');

alter table public.hiring_applications enable row level security;

-- Read-only from the client: an admin sees every application, a lead only
-- their own. There are deliberately no insert/update/delete policies —
-- applicants insert through submit_hiring_application() below, and
-- accept/deny goes through the manage-user edge function (service role).
drop policy if exists "leads read own applications" on public.hiring_applications;
create policy "leads read own applications" on public.hiring_applications for select
  using (public.is_admin() or (public.is_manager() and lead_id = auth.uid()));

-- Applicants aren't signed in, so the public form talks to the database
-- through these two narrow functions instead of the table.
-- Returns the lead's name and whether they're taking applications; no row means
-- the link doesn't point at an active lead.
drop function if exists public.hiring_lead_name(uuid);
drop function if exists public.hiring_lead_info(uuid);
create function public.hiring_lead_info(p_lead_id uuid)
returns table (name text, accepting boolean)
language sql stable security definer set search_path = public
as $$
  select p.name, p.accepting_applications from public.profiles p
  where p.id = p_lead_id and p.role = 'lead' and p.is_active
$$;

grant execute on function public.hiring_lead_info(uuid) to anon, authenticated;

-- The signature gained the computer answers; CREATE OR REPLACE would leave the
-- old 7-argument version callable, letting an applicant skip step 2.
drop function if exists public.submit_hiring_application(uuid, text, text, text, text, text, boolean);
create or replace function public.submit_hiring_application(
  p_lead_id uuid,
  p_remotasks_email text,
  p_remotasks_id text,
  p_full_name text,
  p_active_email text,
  p_facebook_url text,
  p_has_robotics_background boolean,
  p_has_personal_computer boolean,
  p_has_stable_internet boolean,
  p_cpu text,
  p_gpu text,
  p_gpu_memory_gb numeric
)
returns void language plpgsql security definer set search_path = public
as $$
declare
  v_accepting boolean;
  v_remotasks_email text := lower(trim(coalesce(p_remotasks_email, '')));
  v_active_email text := lower(trim(coalesce(p_active_email, '')));
  v_remotasks_id text := trim(coalesce(p_remotasks_id, ''));
  v_full_name text := trim(coalesce(p_full_name, ''));
  v_facebook_url text := trim(coalesce(p_facebook_url, ''));
  v_cpu text := trim(coalesce(p_cpu, ''));
  v_gpu text := trim(coalesce(p_gpu, ''));
begin
  select accepting_applications into v_accepting
  from public.profiles where id = p_lead_id and role = 'lead' and is_active;

  if v_accepting is null then
    raise exception 'This application link is not valid.';
  end if;

  if not v_accepting then
    raise exception 'This lead is not accepting applications right now.';
  end if;

  if v_remotasks_email = '' or v_remotasks_id = '' or v_full_name = '' or v_active_email = '' or v_facebook_url = ''
    or p_has_robotics_background is null or p_has_personal_computer is null or p_has_stable_internet is null then
    raise exception 'Please answer every question.';
  end if;

  if v_remotasks_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' or v_active_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'Please enter a valid email address.';
  end if;

  if v_facebook_url !~* '^https?://\S+$' then
    raise exception 'Please enter your Facebook profile link.';
  end if;

  if p_gpu_memory_gb is not null and (p_gpu_memory_gb < 0 or p_gpu_memory_gb > 256) then
    raise exception 'Please enter your GPU memory in GB (0 if you have no dedicated GPU).';
  end if;

  if char_length(v_remotasks_email) > 254 or char_length(v_active_email) > 254 or char_length(v_remotasks_id) > 200
    or char_length(v_full_name) > 200 or char_length(v_facebook_url) > 500 or char_length(v_cpu) > 200 or char_length(v_gpu) > 200 then
    raise exception 'One of your answers is too long.';
  end if;

  if exists (
    select 1 from public.hiring_applications
    where lead_id = p_lead_id and lower(remotasks_email) = v_remotasks_email and status in ('pending', 'accepted')
  ) then
    raise exception 'An application with this Remotasks email has already been submitted.';
  end if;

  insert into public.hiring_applications
    (lead_id, remotasks_email, remotasks_id, full_name, active_email, facebook_url, has_robotics_background,
     has_personal_computer, has_stable_internet, cpu, gpu, gpu_memory_gb)
  values
    (p_lead_id, v_remotasks_email, v_remotasks_id, v_full_name, v_active_email, v_facebook_url, p_has_robotics_background,
     p_has_personal_computer, p_has_stable_internet, nullif(v_cpu, ''), nullif(v_gpu, ''), p_gpu_memory_gb);
exception
  -- Two submissions racing past the check above hit the unique index instead.
  when unique_violation then
    raise exception 'An application with this Remotasks email has already been submitted.';
end;
$$;

grant execute on function public.submit_hiring_application(uuid, text, text, text, text, text, boolean, boolean, boolean, text, text, numeric) to anon, authenticated;

-- Keep these functions away from signed-out visitors. Postgres (and Supabase's default privileges)
-- makes every new function executable by PUBLIC and anon, and the grants above only ADD authenticated
-- — so without this, anyone holding the public anon key could call them. directory() alone listed
-- every admin and everyone online to a stranger. Left public on purpose: hiring_lead_info() and
-- submit_hiring_application() (the Apply page has no login) and the is_*() helpers (row-level
-- security policies call them, and they only ever return false without a login). Sits at the end so
-- re-running this file after a `drop function` + `create function` doesn't quietly re-open them; add
-- any new signed-in-only function to this list.
do $$
declare fn record;
begin
  for fn in
    select p.oid::regprocedure as sig
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname in (
        'clear_must_change_password', 'contributor_public_stats', 'contributor_public_stats_by_id',
        'directory', 'leaderboard', 'touch_presence', 'update_own_profile', 'conversation_summaries'
      )
  loop
    execute format('revoke execute on function %s from public, anon', fn.sig);
    execute format('grant execute on function %s to authenticated, service_role', fn.sig);
  end loop;
end $$;
