-- Feedback reports (replaces the FEEDBACK Google Sheet): a contributor reports the feedback they
-- got on a task (a screenshot link plus their own remarks), and their lead checks it and marks it
-- valid or not valid, with the lead's own remarks.

create table if not exists public.task_feedback (
  id bigint generated by default as identity primary key,
  -- The contributor who got the feedback and filed the report.
  user_id uuid not null references public.profiles(id) on delete cascade,
  task_id text not null check (char_length(trim(task_id)) between 1 and 100),
  screenshot_url text not null check (screenshot_url ~* '^https?://' and char_length(screenshot_url) <= 1000),
  cb_remarks text check (char_length(cb_remarks) <= 2000),
  status text not null default 'pending' check (status in ('pending', 'valid', 'invalid')),
  lead_remarks text check (char_length(lead_remarks) <= 2000),
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists task_feedback_user_idx on public.task_feedback(user_id, status);
create index if not exists task_feedback_created_at_idx on public.task_feedback(created_at desc);

alter table public.task_feedback enable row level security;

-- A contributor sees their own reports, a lead their attached contributors' (and their own), an
-- admin everyone's.
drop policy if exists "users read permitted feedback" on public.task_feedback;
create policy "users read permitted feedback" on public.task_feedback for select
  using (public.is_admin() or public.is_own_or_attached(user_id));

-- Filed only as yourself and only as pending: the verdict and lead remarks come from
-- review_task_feedback() below.
drop policy if exists "users file own feedback" on public.task_feedback;
create policy "users file own feedback" on public.task_feedback for insert
  with check (
    public.is_active_user()
    and user_id = auth.uid()
    and status = 'pending' and lead_remarks is null and reviewed_by is null and reviewed_at is null
  );

-- A contributor can withdraw their own report while it's still pending; a lead or admin can delete
-- any report they can see.
drop policy if exists "users delete own or managed feedback" on public.task_feedback;
create policy "users delete own or managed feedback" on public.task_feedback for delete
  using (
    public.is_admin()
    or (public.is_manager() and public.is_own_or_attached(user_id) and user_id <> auth.uid())
    or (user_id = auth.uid() and status = 'pending')
  );

-- No update policy: the only change after filing is the lead's check, made through here so a
-- contributor can't mark their own report. A report can be checked again to change the verdict or
-- remarks. Leads check their attached contributors' reports (not their own); admins check any.
create or replace function public.review_task_feedback(p_id bigint, p_status text, p_remarks text)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if p_status not in ('valid', 'invalid') then
    raise exception 'A report is marked valid or invalid.';
  end if;

  update public.task_feedback f
  set status = p_status,
      lead_remarks = nullif(trim(coalesce(p_remarks, '')), ''),
      reviewed_by = auth.uid(),
      reviewed_at = now()
  where f.id = p_id
    and (
      public.is_admin()
      or (public.is_manager() and public.is_own_or_attached(f.user_id) and f.user_id <> auth.uid())
    );

  if not found then
    raise exception 'Report not found, or not one you can check.';
  end if;
end;
$$;

grant execute on function public.review_task_feedback(bigint, text, text) to authenticated;

-- Signed-in people only (new functions are executable by everyone by default).
revoke execute on function public.review_task_feedback(bigint, text, text) from public, anon;
