-- Team features: an audit log of manager actions, announcements, the new-hire onboarding
-- checklist, streaks & badges, and group chats. Safe to re-run. The same statements are in
-- schema.sql.

-- directory() now also returns lead_id (to managers only), so the group-chat member picker can
-- fill in a whole team or project in one click. The return type changes, hence drop + create.
drop function if exists public.directory();
create function public.directory()
returns table (id uuid, name text, is_active boolean, last_seen_at timestamptz, avatar_url text, role text, is_bot boolean, email text, lead_id uuid)
language sql stable security definer set search_path = public
as $$
  select p.id, p.name, p.is_active,
    case when public.is_manager() or p.last_seen_at > now() - interval '3 minutes' then p.last_seen_at end,
    p.avatar_url, p.role, p.is_bot,
    case when public.is_manager() then p.email end,
    case when public.is_manager() then p.lead_id end
  from public.profiles p
  where p.is_active and public.is_active_user() and (
    public.is_manager()
    or p.is_bot
    or p.role = 'admin'
    or p.last_seen_at > now() - interval '3 minutes'
    or p.id = (select me.lead_id from public.profiles me where me.id = auth.uid())
    or exists (
      select 1 from public.messages m
      where (m.sender_id = auth.uid() and m.recipient_id = p.id)
         or (m.recipient_id = auth.uid() and m.sender_id = p.id)
    )
  )
$$;

grant execute on function public.directory() to authenticated;

-- ============================================================================================
-- Audit log: which manager did what, to whom. activity_logs only covers sign-ins; this covers
-- role/team/account changes, request reviews, levels, targets, projects and deleted tasks.
-- Rows come only from the triggers below (changes made through the app as a signed-in user) and
-- from the manage-user edge function (account and hiring actions, which run as the service role
-- and so carry no auth.uid() for a trigger to record). Admins read it; nobody can edit or delete
-- it through the API, which is the point of an audit trail.
-- ============================================================================================
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null check (char_length(action) between 1 and 60),
  target_user_id uuid references public.profiles(id) on delete set null,
  summary text not null check (char_length(summary) between 1 and 500),
  details jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);
create index if not exists audit_logs_target_idx on public.audit_logs(target_user_id);

alter table public.audit_logs enable row level security;
drop policy if exists "admins read audit logs" on public.audit_logs;
create policy "admins read audit logs" on public.audit_logs for select using (public.is_admin());

-- Records one action by the signed-in caller. No caller (service role, SQL editor) means nothing
-- is recorded here: manage-user writes its own rows, and SQL-editor changes aren't app actions.
create or replace function public.write_audit(p_action text, p_target uuid, p_summary text, p_details jsonb default null)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is null then
    return;
  end if;
  insert into public.audit_logs (actor_id, action, target_user_id, summary, details)
  values (auth.uid(), p_action, p_target, left(p_summary, 500), p_details);
end;
$$;

-- Only the triggers below call it; a client calling it directly could write made-up history.
revoke execute on function public.write_audit(text, uuid, text, jsonb) from public, anon, authenticated;

create or replace function public.audit_profile_changes()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  old_lead text;
  new_lead text;
begin
  if auth.uid() is null then
    return null;
  end if;
  if new.role is distinct from old.role then
    perform public.write_audit('role_changed', new.id,
      format('Changed %s''s role from %s to %s', new.name, old.role, new.role),
      jsonb_build_object('from', old.role, 'to', new.role));
  end if;
  if new.lead_id is distinct from old.lead_id then
    select name into old_lead from public.profiles where id = old.lead_id;
    select name into new_lead from public.profiles where id = new.lead_id;
    perform public.write_audit('lead_changed', new.id,
      case when new.lead_id is null
        then format('Removed %s from %s''s team', new.name, coalesce(old_lead, 'their lead'))
        else format('Moved %s to %s''s team', new.name, coalesce(new_lead, 'another lead'))
      end,
      jsonb_build_object('from', old.lead_id, 'to', new.lead_id));
  end if;
  if new.is_active is distinct from old.is_active then
    perform public.write_audit(case when new.is_active then 'account_enabled' else 'account_disabled' end, new.id,
      format('%s %s''s account', case when new.is_active then 'Enabled' else 'Disabled' end, new.name));
  end if;
  -- Renaming yourself (Edit Profile) isn't a manager action.
  if new.name is distinct from old.name and new.id <> auth.uid() then
    perform public.write_audit('profile_renamed', new.id, format('Renamed %s to %s', old.name, new.name),
      jsonb_build_object('from', old.name, 'to', new.name));
  end if;
  return null;
end;
$$;

drop trigger if exists profiles_audit on public.profiles;
create trigger profiles_audit after update on public.profiles
  for each row execute function public.audit_profile_changes();

create or replace function public.audit_request_review()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  who text;
  task text;
begin
  if auth.uid() is null or new.status is not distinct from old.status or new.status = 'pending' then
    return null;
  end if;
  select name into who from public.profiles where id = new.requested_by;
  select task_id into task from public.task_submissions where id = new.task_submission_id;
  perform public.write_audit('request_' || new.status, new.requested_by,
    format('%s %s''s %s%s', initcap(new.status), coalesce(who, 'someone'),
      case new.type when 'bad_video' then 'bad video report' else new.type || ' request' end,
      coalesce(' for task ' || task, '')),
    jsonb_build_object('request_id', new.id, 'type', new.type));
  return null;
end;
$$;

drop trigger if exists task_requests_audit on public.task_requests;
create trigger task_requests_audit after update on public.task_requests
  for each row execute function public.audit_request_review();

create or replace function public.audit_level_change()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  r public.contributor_project_levels;
  who text;
  project text;
begin
  if auth.uid() is null then
    return null;
  end if;
  if tg_op = 'UPDATE' and new.level is not distinct from old.level then
    return null;
  end if;
  if tg_op = 'DELETE' then r := old; else r := new; end if;
  select name into who from public.profiles where id = r.user_id;
  select name into project from public.projects where id = r.project_id;
  -- Deleting a project or a person cascades here; that deletion is what gets recorded.
  if who is null or project is null then
    return null;
  end if;
  perform public.write_audit('level_changed', r.user_id,
    case when tg_op = 'DELETE'
      then format('Cleared %s''s level on %s', who, project)
      else format('Set %s''s level on %s to %s', who, project,
        case when r.level = 'contributor' then 'Contributor' else upper(r.level) end)
    end,
    jsonb_build_object('project_id', r.project_id, 'level', case when tg_op = 'DELETE' then null else r.level end));
  return null;
end;
$$;

drop trigger if exists contributor_project_levels_audit on public.contributor_project_levels;
create trigger contributor_project_levels_audit after insert or update or delete on public.contributor_project_levels
  for each row execute function public.audit_level_change();

create or replace function public.audit_target_change()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  who text;
begin
  if auth.uid() is null or (tg_op = 'UPDATE' and new.target is not distinct from old.target) then
    return null;
  end if;
  select name into who from public.profiles where id = new.user_id;
  perform public.write_audit('target_changed', new.user_id,
    format('Set %s''s weekly target to %s for the week of %s', coalesce(who, 'someone'), new.target, to_char(new.week_start, 'Mon FMDD, YYYY')),
    jsonb_build_object('week_start', new.week_start, 'from', case when tg_op = 'UPDATE' then old.target end, 'to', new.target));
  return null;
end;
$$;

drop trigger if exists weekly_targets_audit on public.weekly_targets;
create trigger weekly_targets_audit after insert or update on public.weekly_targets
  for each row execute function public.audit_target_change();

create or replace function public.audit_project_change()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is null then
    return null;
  end if;
  if tg_op = 'INSERT' then
    perform public.write_audit('project_created', null, format('Created project %s', new.name), jsonb_build_object('project_id', new.id));
  elsif tg_op = 'DELETE' then
    perform public.write_audit('project_deleted', null, format('Deleted project %s', old.name), jsonb_build_object('project_id', old.id));
  elsif new.name is distinct from old.name then
    perform public.write_audit('project_renamed', null, format('Renamed project %s to %s', old.name, new.name), jsonb_build_object('project_id', new.id));
  end if;
  return null;
end;
$$;

drop trigger if exists projects_audit on public.projects;
create trigger projects_audit after insert or update or delete on public.projects
  for each row execute function public.audit_project_change();

create or replace function public.audit_project_lead_change()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  r public.project_leads;
  who text;
  project text;
begin
  if auth.uid() is null then
    return null;
  end if;
  if tg_op = 'DELETE' then r := old; else r := new; end if;
  select name into who from public.profiles where id = r.lead_id;
  select name into project from public.projects where id = r.project_id;
  if who is null or project is null then
    return null;
  end if;
  perform public.write_audit(case when tg_op = 'DELETE' then 'project_lead_removed' else 'project_lead_added' end, r.lead_id,
    case when tg_op = 'DELETE'
      then format('Removed %s as a lead of %s', who, project)
      else format('Made %s a lead of %s', who, project)
    end,
    jsonb_build_object('project_id', r.project_id));
  return null;
end;
$$;

drop trigger if exists project_leads_audit on public.project_leads;
create trigger project_leads_audit after insert or delete on public.project_leads
  for each row execute function public.audit_project_lead_change();

-- A task deleted by someone other than the contributor it belongs to (a lead or admin cleaning up).
create or replace function public.audit_submission_delete()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  owner_id uuid;
begin
  if auth.uid() is null then
    return null;
  end if;
  select id into owner_id from public.profiles where lower(email) = lower(old.cb_email);
  if owner_id = auth.uid() then
    return null;
  end if;
  perform public.write_audit('submission_deleted', owner_id,
    format('Deleted task %s%s logged for %s', coalesce(old.task_id, '(no ID)'), coalesce(' from ' || old.date::text, ''), old.cb_email),
    jsonb_build_object('task_id', old.task_id, 'status', old.status, 'stage', old.stage, 'date', old.date));
  return null;
end;
$$;

drop trigger if exists task_submissions_audit_delete on public.task_submissions;
create trigger task_submissions_audit_delete after delete on public.task_submissions
  for each row execute function public.audit_submission_delete();

-- ============================================================================================
-- Announcements: a post from a lead or admin to everyone, one lead's team, or one project, with
-- who has seen it. Posting rules: everyone = admins only; a team = that team's lead (or an admin);
-- a project = one of its leads (or an admin). The audience matches the rest of the app's scoping:
-- a team is the lead plus contributors whose lead_id is them; a project is its leads plus their
-- contributors (can_view_project()).
-- ============================================================================================
create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  audience text not null check (audience in ('everyone', 'team', 'project')),
  team_lead_id uuid references public.profiles(id) on delete cascade,
  project_id bigint references public.projects(id) on delete cascade,
  title text not null check (char_length(trim(title)) between 1 and 120),
  body text not null check (char_length(trim(body)) between 1 and 4000),
  pinned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint announcements_audience_target check (
    (audience = 'everyone' and team_lead_id is null and project_id is null)
    or (audience = 'team' and team_lead_id is not null and project_id is null)
    or (audience = 'project' and project_id is not null and team_lead_id is null)
  )
);

create table if not exists public.announcement_reads (
  announcement_id bigint not null references public.announcements(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (announcement_id, user_id)
);

create index if not exists announcements_created_idx on public.announcements(pinned desc, created_at desc);
create index if not exists announcement_reads_user_idx on public.announcement_reads(user_id);

-- Whether an announcement is meant for the caller (not just visible to them: an admin can see
-- every team's posts, but a team post isn't addressed to them, so it never counts as unread and
-- their viewing it doesn't count as the team having seen it).
create or replace function public.announcement_addressed_to_me(p_audience text, p_team_lead_id uuid, p_project_id bigint)
returns boolean language sql stable security definer set search_path = public
as $$
  select public.is_active_user() and (
    p_audience = 'everyone'
    or (p_audience = 'team' and (
      p_team_lead_id = auth.uid()
      or exists (select 1 from public.profiles me where me.id = auth.uid() and me.lead_id = p_team_lead_id)
    ))
    or (p_audience = 'project' and (
      public.is_project_lead(p_project_id)
      or exists (
        select 1 from public.profiles me join public.project_leads pl on pl.lead_id = me.lead_id
        where me.id = auth.uid() and pl.project_id = p_project_id
      )
    ))
  )
$$;

create or replace function public.can_post_announcement(p_audience text, p_team_lead_id uuid, p_project_id bigint)
returns boolean language sql stable security definer set search_path = public
as $$
  select public.is_admin() or (
    public.is_manager() and (
      (p_audience = 'team' and p_team_lead_id = auth.uid())
      or (p_audience = 'project' and public.is_project_lead(p_project_id))
    )
  )
$$;

alter table public.announcements enable row level security;
alter table public.announcement_reads enable row level security;

drop policy if exists "users read announcements for them" on public.announcements;
create policy "users read announcements for them" on public.announcements for select
  using (
    public.is_admin()
    or author_id = auth.uid()
    or public.announcement_addressed_to_me(audience, team_lead_id, project_id)
  );
drop policy if exists "managers post announcements" on public.announcements;
create policy "managers post announcements" on public.announcements for insert
  with check (author_id = auth.uid() and public.can_post_announcement(audience, team_lead_id, project_id));
drop policy if exists "authors or admins update announcements" on public.announcements;
create policy "authors or admins update announcements" on public.announcements for update
  using (public.is_admin() or (author_id = auth.uid() and public.is_manager()))
  with check (public.is_admin() or (author_id = auth.uid() and public.can_post_announcement(audience, team_lead_id, project_id)));
drop policy if exists "authors or admins delete announcements" on public.announcements;
create policy "authors or admins delete announcements" on public.announcements for delete
  using (public.is_admin() or author_id = auth.uid());

-- Your own reads; reads are written only by mark_announcements_read() below.
drop policy if exists "users read own announcement reads" on public.announcement_reads;
create policy "users read own announcement reads" on public.announcement_reads for select
  using (user_id = auth.uid());

-- Marks every announcement addressed to the caller as seen (the Announcements page calls it on open).
create or replace function public.mark_announcements_read()
returns void language sql security definer set search_path = public
as $$
  insert into public.announcement_reads (announcement_id, user_id)
  select a.id, auth.uid() from public.announcements a
  where public.announcement_addressed_to_me(a.audience, a.team_lead_id, a.project_id)
    and a.author_id <> auth.uid()
  on conflict do nothing
$$;

grant execute on function public.mark_announcements_read() to authenticated;

create or replace function public.unread_announcement_count()
returns bigint language sql stable security definer set search_path = public
as $$
  select count(*) from public.announcements a
  where public.announcement_addressed_to_me(a.audience, a.team_lead_id, a.project_id)
    and a.author_id <> auth.uid()
    and not exists (select 1 from public.announcement_reads r where r.announcement_id = a.id and r.user_id = auth.uid())
$$;

grant execute on function public.unread_announcement_count() to authenticated;

-- Who an announcement is for and who has seen it, for its author or an admin. Names come from
-- here rather than profiles, whose read policy wouldn't show a lead the other teams on a project.
create or replace function public.announcement_seen_by(p_announcement_id bigint)
returns table (user_id uuid, name text, avatar_url text, read_at timestamptz)
language sql stable security definer set search_path = public
as $$
  with a as (
    select * from public.announcements
    where id = p_announcement_id and (public.is_admin() or author_id = auth.uid()) and public.is_active_user()
  ),
  audience as (
    select a.id as announcement_id, p.id, p.name, p.avatar_url from public.profiles p, a
    where p.is_active and not p.is_bot and p.id <> a.author_id and (
      a.audience = 'everyone'
      or (a.audience = 'team' and (p.id = a.team_lead_id or p.lead_id = a.team_lead_id))
      or (a.audience = 'project' and (
        exists (select 1 from public.project_leads pl where pl.project_id = a.project_id and pl.lead_id = p.id)
        or exists (select 1 from public.project_leads pl where pl.project_id = a.project_id and pl.lead_id = p.lead_id)
      ))
    )
  )
  select au.id, au.name, au.avatar_url, r.read_at
  from audience au
  left join public.announcement_reads r on r.announcement_id = au.announcement_id and r.user_id = au.id
  order by r.read_at desc nulls last, au.name
$$;

grant execute on function public.announcement_seen_by(bigint) to authenticated;

create or replace function public.audit_announcement()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  target_name text;
begin
  if new.audience = 'team' then
    select name || '''s team' into target_name from public.profiles where id = new.team_lead_id;
  elsif new.audience = 'project' then
    select 'project ' || name into target_name from public.projects where id = new.project_id;
  end if;
  perform public.write_audit('announcement_posted', null,
    format('Posted "%s" to %s', new.title, coalesce(target_name, 'everyone')),
    jsonb_build_object('announcement_id', new.id));
  return null;
end;
$$;

drop trigger if exists announcements_audit on public.announcements;
create trigger announcements_audit after insert on public.announcements
  for each row execute function public.audit_announcement();

-- ============================================================================================
-- Onboarding checklist for new contributors. Most steps are read from real data (a photo, a
-- Remotasks ID, a shift, a first task, a first message to their lead); the two that can't be
-- (reading the guides, and hiding the checklist) are ticked by the contributor and kept here.
-- ============================================================================================
alter table public.profiles add column if not exists onboarding jsonb not null default '{}'::jsonb
  check (jsonb_typeof(onboarding) = 'object' and pg_column_size(onboarding) <= 1024);

create or replace function public.complete_onboarding_step(p_step text, p_done boolean default true)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if p_step not in ('read_resources', 'dismissed') then
    raise exception 'Unknown onboarding step.';
  end if;
  update public.profiles
  set onboarding = case when p_done
      then onboarding || jsonb_build_object(p_step, now())
      else onboarding - p_step
    end
  where id = auth.uid() and public.is_active_user();
end;
$$;

grant execute on function public.complete_onboarding_step(text, boolean) to authenticated;

-- Checklist state for the given contributors: the caller themselves, their own team (a lead), or
-- anyone (an admin). Others are silently left out, so a list of ids is safe to pass as-is.
create or replace function public.onboarding_status(p_user_ids uuid[])
returns table (user_id uuid, steps jsonb, done integer, total integer, dismissed boolean)
language sql stable security definer set search_path = public
as $$
  with people as (
    select p.* from public.profiles p
    where p.id = any(p_user_ids) and p.role = 'contributor'
      and (public.is_admin() or public.is_own_or_attached(p.id))
  ),
  checks as (
    select pe.id,
      jsonb_build_object(
        'photo', pe.avatar_url is not null,
        'remotasks_id', pe.remotasks_id is not null,
        'shift', pe.shift is not null,
        'read_resources', pe.onboarding ? 'read_resources',
        'first_task', exists (
          select 1 from public.task_submissions s where s.user_id = pe.id or lower(s.cb_email) = lower(pe.email)
        ),
        'message_lead', pe.lead_id is not null and exists (
          select 1 from public.messages m where m.sender_id = pe.id and m.recipient_id = pe.lead_id
        )
      ) as steps,
      pe.lead_id is not null as has_lead,
      pe.onboarding ? 'dismissed' as dismissed
    from people pe
  )
  select c.id, c.steps,
    (select count(*) from jsonb_each(c.steps) e where e.value = 'true'::jsonb and (c.has_lead or e.key <> 'message_lead'))::integer,
    (case when c.has_lead then 6 else 5 end)::integer,
    c.dismissed
  from checks c
$$;

grant execute on function public.onboarding_status(uuid[]) to authenticated;

-- ============================================================================================
-- Streaks & badges. A week is the business week (Tuesday to Monday, Asia/Singapore). A week is
-- "hit" when the contributor submitted at least their target for it (50 unless set) and at least
-- one task. The current streak counts hit weeks back from the last finished week, plus this week
-- once it's hit; an unfinished week never breaks a streak. Public like contributor_public_stats():
-- only rollups, for contributors, to any active user.
-- ============================================================================================
create or replace function public.contributor_achievements(p_user_ids uuid[])
returns table (user_id uuid, current_streak integer, best_streak integer, weeks_hit integer, total_submitted bigint, best_week bigint)
language sql stable security definer set search_path = public
as $$
  with cw as (
    select d - ((extract(isodow from d)::int + 5) % 7) as ws
    from (select (now() at time zone 'Asia/Singapore')::date as d) t
  ),
  people as (
    select p.id, p.email from public.profiles p
    where p.id = any(p_user_ids) and p.role = 'contributor' and public.is_active_user()
  ),
  weekly as (
    select pe.id as user_id, (s.date - ((extract(isodow from s.date)::int + 5) % 7)) as week_start, count(*) as n
    from people pe
    join public.task_submissions s
      on s.status = 'submitted' and s.date is not null
     and (s.user_id = pe.id or lower(s.cb_email) = lower(pe.email))
    group by 1, 2
  ),
  weeks as (
    select f.user_id, gs::date as week_start
    from (select w.user_id, min(w.week_start) as first_week from weekly w group by w.user_id) f
    cross join lateral generate_series(f.first_week::timestamp, (select ws from cw)::timestamp, interval '7 days') gs
  ),
  flags as (
    select w.user_id, w.week_start, coalesce(wk.n, 0) as n,
      coalesce(wk.n, 0) > 0 and coalesce(wk.n, 0) >= coalesce(t.target, 50) as hit,
      w.week_start = (select ws from cw) as is_current
    from weeks w
    left join weekly wk on wk.user_id = w.user_id and wk.week_start = w.week_start
    left join public.weekly_targets t on t.user_id = w.user_id and t.week_start = w.week_start
  ),
  counted as (
    select * from flags where not is_current or hit
  ),
  islands as (
    select user_id, week_start, hit,
      row_number() over (partition by user_id order by week_start)
        - row_number() over (partition by user_id, hit order by week_start) as grp
    from counted
  ),
  runs as (
    select user_id, count(*)::integer as len, max(week_start) as last_week
    from islands where hit group by user_id, grp
  )
  select pe.id,
    coalesce((select r.len from runs r where r.user_id = pe.id and r.last_week >= (select ws from cw) - 7 order by r.last_week desc limit 1), 0),
    coalesce((select max(r.len) from runs r where r.user_id = pe.id), 0),
    (select count(*) from flags f where f.user_id = pe.id and f.hit)::integer,
    coalesce((select sum(w.n) from weekly w where w.user_id = pe.id), 0)::bigint,
    coalesce((select max(w.n) from weekly w where w.user_id = pe.id), 0)::bigint
  from people pe
$$;

grant execute on function public.contributor_achievements(uuid[]) to authenticated;

-- ============================================================================================
-- Group chats. Leads and admins create groups (e.g. a whole team or project); members chat in
-- them. Every change to a group or its membership goes through the functions below; the tables
-- only allow reading (members only) and posting a message into a group you're in.
-- ============================================================================================
create table if not exists public.chat_groups (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 80),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_group_members (
  group_id bigint not null references public.chat_groups(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'member')),
  last_read_at timestamptz not null default now(),
  joined_at timestamptz not null default now(),
  primary key (group_id, user_id)
);

create table if not exists public.group_messages (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.chat_groups(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) > 0 and char_length(body) <= 2000),
  created_at timestamptz not null default now()
);

create index if not exists chat_group_members_user_idx on public.chat_group_members(user_id);
create index if not exists group_messages_group_idx on public.group_messages(group_id, id desc);

create or replace function public.is_group_member(p_group_id bigint)
returns boolean language sql stable security definer set search_path = public
as $$
  select public.is_active_user() and exists (
    select 1 from public.chat_group_members where group_id = p_group_id and user_id = auth.uid()
  )
$$;

-- The group's owner (its creator, or whoever they handed it to) or an admin who is in it.
create or replace function public.can_manage_group(p_group_id bigint)
returns boolean language sql stable security definer set search_path = public
as $$
  select public.is_active_user() and exists (
    select 1 from public.chat_group_members
    where group_id = p_group_id and user_id = auth.uid() and (role = 'owner' or public.is_admin())
  )
$$;

alter table public.chat_groups enable row level security;
alter table public.chat_group_members enable row level security;
alter table public.group_messages enable row level security;

drop policy if exists "members read groups" on public.chat_groups;
create policy "members read groups" on public.chat_groups for select using (public.is_group_member(id));
drop policy if exists "members read group members" on public.chat_group_members;
create policy "members read group members" on public.chat_group_members for select using (public.is_group_member(group_id));
drop policy if exists "members read group messages" on public.group_messages;
create policy "members read group messages" on public.group_messages for select using (public.is_group_member(group_id));
drop policy if exists "members post group messages" on public.group_messages;
create policy "members post group messages" on public.group_messages for insert
  with check (sender_id = auth.uid() and public.is_group_member(group_id));

-- Same spam guard as direct messages: 30 a minute across all groups.
create or replace function public.enforce_group_message_limits()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if (select count(*) from public.group_messages where sender_id = new.sender_id and created_at > now() - interval '60 seconds') >= 30 then
    raise exception 'You are sending messages too fast. Please wait a moment.';
  end if;
  return new;
end;
$$;

drop trigger if exists group_messages_enforce_limits on public.group_messages;
create trigger group_messages_enforce_limits before insert on public.group_messages
  for each row execute function public.enforce_group_message_limits();

create or replace function public.create_chat_group(p_name text, p_member_ids uuid[])
returns bigint language plpgsql security definer set search_path = public
as $$
declare
  new_id bigint;
begin
  if not public.is_manager() then
    raise exception 'Only leads and admins can create group chats.';
  end if;
  if p_name is null or char_length(trim(p_name)) = 0 then
    raise exception 'Give the group a name.';
  end if;
  insert into public.chat_groups (name, created_by) values (trim(p_name), auth.uid()) returning id into new_id;
  insert into public.chat_group_members (group_id, user_id, role) values (new_id, auth.uid(), 'owner');
  insert into public.chat_group_members (group_id, user_id)
  select new_id, p.id from public.profiles p
  where p.id = any(coalesce(p_member_ids, '{}')) and p.id <> auth.uid() and p.is_active and not p.is_bot
  on conflict do nothing;
  return new_id;
end;
$$;

create or replace function public.add_chat_group_members(p_group_id bigint, p_member_ids uuid[])
returns void language plpgsql security definer set search_path = public
as $$
begin
  if not public.can_manage_group(p_group_id) then
    raise exception 'Only the group''s owner or an admin can add people.';
  end if;
  insert into public.chat_group_members (group_id, user_id, last_read_at)
  select p_group_id, p.id, now() from public.profiles p
  where p.id = any(coalesce(p_member_ids, '{}')) and p.is_active and not p.is_bot
  on conflict do nothing;
end;
$$;

-- Removes someone (owner/admin), or yourself (leaving). A group whose last member leaves is deleted.
create or replace function public.remove_chat_group_member(p_group_id bigint, p_user_id uuid)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if p_user_id <> auth.uid() and not public.can_manage_group(p_group_id) then
    raise exception 'Only the group''s owner or an admin can remove people.';
  end if;
  if not public.is_group_member(p_group_id) then
    raise exception 'You are not in this group.';
  end if;
  delete from public.chat_group_members where group_id = p_group_id and user_id = p_user_id;
  if not exists (select 1 from public.chat_group_members where group_id = p_group_id) then
    delete from public.chat_groups where id = p_group_id;
  elsif not exists (select 1 from public.chat_group_members where group_id = p_group_id and role = 'owner') then
    -- The owner left: hand the group to whoever has been in it longest.
    update public.chat_group_members set role = 'owner'
    where (group_id, user_id) = (
      select group_id, user_id from public.chat_group_members where group_id = p_group_id order by joined_at limit 1
    );
  end if;
end;
$$;

create or replace function public.rename_chat_group(p_group_id bigint, p_name text)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if not public.can_manage_group(p_group_id) then
    raise exception 'Only the group''s owner or an admin can rename it.';
  end if;
  if p_name is null or char_length(trim(p_name)) = 0 then
    raise exception 'Give the group a name.';
  end if;
  update public.chat_groups set name = trim(p_name) where id = p_group_id;
end;
$$;

create or replace function public.delete_chat_group(p_group_id bigint)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if not public.can_manage_group(p_group_id) then
    raise exception 'Only the group''s owner or an admin can delete it.';
  end if;
  delete from public.chat_groups where id = p_group_id;
end;
$$;

create or replace function public.mark_chat_group_read(p_group_id bigint)
returns void language sql security definer set search_path = public
as $$
  update public.chat_group_members set last_read_at = now() where group_id = p_group_id and user_id = auth.uid()
$$;

-- The caller's groups for the inbox: members (names and photos, which profiles' read policy
-- wouldn't show a contributor), unread count and the latest message.
create or replace function public.chat_group_summaries()
returns table (id bigint, name text, my_role text, created_at timestamptz, unread_count bigint, last_message jsonb, members jsonb)
language sql stable security definer set search_path = public
as $$
  select g.id, g.name, me.role, g.created_at,
    (select count(*) from public.group_messages m
      where m.group_id = g.id and m.created_at > me.last_read_at and m.sender_id <> auth.uid()),
    (select to_jsonb(m) from public.group_messages m where m.group_id = g.id order by m.id desc limit 1),
    (select coalesce(jsonb_agg(jsonb_build_object('id', p.id, 'name', p.name, 'avatar_url', p.avatar_url, 'role', cm.role) order by p.name), '[]'::jsonb)
      from public.chat_group_members cm join public.profiles p on p.id = cm.user_id where cm.group_id = g.id)
  from public.chat_groups g
  join public.chat_group_members me on me.group_id = g.id and me.user_id = auth.uid()
  where public.is_active_user()
$$;

grant execute on function public.create_chat_group(text, uuid[]) to authenticated;
grant execute on function public.add_chat_group_members(bigint, uuid[]) to authenticated;
grant execute on function public.remove_chat_group_member(bigint, uuid) to authenticated;
grant execute on function public.rename_chat_group(bigint, text) to authenticated;
grant execute on function public.delete_chat_group(bigint) to authenticated;
grant execute on function public.mark_chat_group_read(bigint) to authenticated;
grant execute on function public.chat_group_summaries() to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'group_messages'
  ) then
    alter publication supabase_realtime add table public.group_messages;
  end if;
end $$;

-- Signed-in only, like the functions at the end of schema.sql.
do $$
declare fn record;
begin
  for fn in
    select p.oid::regprocedure as sig
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname in (
        'directory', 'mark_announcements_read', 'unread_announcement_count', 'announcement_seen_by',
        'complete_onboarding_step', 'onboarding_status', 'contributor_achievements',
        'create_chat_group', 'add_chat_group_members', 'remove_chat_group_member', 'rename_chat_group',
        'delete_chat_group', 'mark_chat_group_read', 'chat_group_summaries'
      )
  loop
    execute format('revoke execute on function %s from public, anon', fn.sig);
    execute format('grant execute on function %s to authenticated, service_role', fn.sig);
  end loop;
end $$;
